import Navbar from '@/components/Navbar/Navbar';
import { Quicksand } from 'next/font/google';
import './styles.css';

const quicksandFont = Quicksand({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang={'en'}>
    <body className={quicksandFont.className}>
      <div className={'app'}>
        <Navbar />
        <div className={'content'}>{children}</div>
      </div>
    </body>
  </html>
);

export default RootLayout;
